org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false

# Java config
java_version=25

# Minecraft version
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)

# NeoForge
neoforge_version=26.3.0.57-beta
neoforge_loader_version_range=[21,)
loader_version_range=[4,)

# Forge
forge_version=66.0.9
forge_version_range=[66,)
forge_loader_version_range=[66,)
eventbus_version=7.0.5
bootstrap_version=2.1.8

# Fabric
fabric_loader_version=0.19.5
fabric_api_version=0.162.0+26.3

## Mod Properties
mod_id=carryme
mod_name=Carry Me
mod_version=1.0

mod_license=Apache 2.0

mod_group_id=com.pedrorok
mod_authors=Rok
mod_description=Carry Me allows you to choose whether you can be carried or not

# Dependencies
carry_on_version=2.12.0
