org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false

# Java config
java_version=25

# Minecraft version
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)

# NeoForge
neoforge_version=26.1.2.94
neoforge_loader_version_range=[21,)
loader_version_range=[4,)

# Forge
forge_version=64.1.0
forge_version_range=[64,)
forge_loader_version_range=[64,)
eventbus_version=7.0.5
bootstrap_version=2.1.8

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

## Mod Properties
mod_id=carryme
mod_name=Carry Me
mod_version=1.0

mod_license=Apache 2.0

mod_group_id=com.pedrorok
mod_authors=Rok
mod_description=Carry Me allows you to choose whether you can be carried or not

# Dependencies
carry_on_version=2.10.0
